version: '1'
services:
  wiremock:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./stubs_folder1:/wiremock/stubs_folder1
      - ./stubs_folder2:/wiremock/stubs_folder2
    ports:
      - "8080:8080"
    user: "appuser"